Metrics/LineLength:
  Max: 100

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Max: 16

Metrics/AbcSize:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 10
  
Metrics/CyclomaticComplexity:
  Max: 10

Style/ClassVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false
